// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Alterna para a DIRECT_URL se a flag PRISMA_MIGRATE estiver ativa
const connectionUrl =
  process.env.PRISMA_MIGRATE === "true"
    ? env("DIRECT_URL")
    : env("DATABASE_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: connectionUrl,
  },
});
