// Next.js
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import localFont from "next/font/local";
import { Lato } from "next/font/google";

// Next-Intl
import { routing } from "@/i18n/routing";
import { hasLocale, NextIntlClientProvider } from "next-intl";

// Theme Provider
import { ThemeProvider } from "@/components/theme-provider";

// Utils & CSS
import { cn } from "@/lib/utils";
import "./globals.css";

const lato = Lato({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
});

const perfectlyNineties = localFont({
  src: [
    {
      path: "../../assets/fonts/PerfectlyNinetiesOTF/PerfectlyNineties-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/PerfectlyNinetiesOTF/PerfectlyNineties-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../assets/fonts/PerfectlyNinetiesOTF/PerfectlyNineties-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../assets/fonts/PerfectlyNinetiesOTF/PerfectlyNineties-Extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../assets/fonts/PerfectlyNinetiesOTF/PerfectlyNineties-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-perfectly-nineties",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        lato.variable,
        perfectlyNineties.variable,
        "font-sans",
      )}
    >
      <NextIntlClientProvider>
        <body className="min-h-full flex flex-col">
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            forcedTheme="light"
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
